export const CATEGORY = {
  university: [
    'University of Ghana',
    'Kwame Nkrumah University of Science and Technology',
    'University of Cape Coast',
    'University of Education, Winneba',
    'Akenten Appiah Menkah University of Skills Training and Entrepreneurial Development, Kumasi',
    'University for Development Studies',
    'University of Professional Studies',
    'University of Mines and Technology',
    'University of Health and Allied Sciences',
    'University of Energy and Natural Resources',
    'Accra Technical University',
    'Bolgatanga Technical University',
    'Cape Coast Technical University',
    'Kumasi Technical University',
    'Koforidua Technical University',
    'Tamale Technical University',
    'Ho Technical University',
    'Takoradi Technical University',
    'Sunyani Technical University',
    'Wa Technical University',
    'Ghana Institute of Journalism',
    'Ghana Institute of Languages',
    'University of Professional Studies, Accra',
    'Regional Maritime University',
    'Valley View University',
    'Central University',
    'Pentecost University',
    'All Nations University',
    'Ashesi University',
    'Accra Institute of Technology',
    'Catholic University College of Ghana',
    'Christian Service University College',
    'Islamic University College',
    'Knutsford University College',
    'Lancaster University',
    'Methodist University College Ghana',
    'Presbyterian University College',
    'Wisconsin International University College',
    'Central University College',
    'Catholic Institute of Business and Technology',
    'Garden City University College',
    'Regent University College of Science and Technology',
    'Spiritan University College',
    'Webster University Ghana Campus',
    'Ghana Christian University College',
    'Zenith University College',
  ],
  exams: [
    'BECE',
    'BECE(Private)',
    'WASSCE(School)',
    'WASSCE(Private)',
    'NOV-DEC',
    'CSSPS PLACEMENT',
    'SSSCE',
    'ABCE',
    'GBCE',
  ],
  security: [
    'Ghana Immigration Service',
    'Ghana Police Service',
    'Ghana Fire Service',
    'Ghana Armed Forces Command and Staff College',
  ],
};

export const PAGES = [
  {
    title: 'Waec Checker',
    category: 'Waec Checker',
    note: 'Note',
    type: 'waec',
    route: 'add-waec-checker',
  },
  {
    title: 'University Forms',
    category: 'University',
    note: 'Note',
    type: 'university',
    route: 'add-university-forms',
  },
  {
    title: 'Security Service Forms',
    category: 'Security Service',
    note: 'Note',
    type: 'security',
    route: 'add-security-service',
  },
  {
    title: 'Cinema Tickets',
    category: 'Cinema Ticket',
    note: 'Note',
    type: 'cinema',
    route: 'add-cinema-tickets',
  },
  {
    title: 'Stadium Tickets',
    category: 'Stadium Ticket',
    note: 'Note',
    type: 'stadium',
    route: 'add-stadia-tickets',
  },
  {
    title: 'Bus Tickets',
    category: 'Bus Ticket',
    note: 'Note',
    type: 'bus',
    route: 'add-bus-tickets',
  },
];
