import {
  DashboardRounded,
  CarRentalRounded,
  KeySharp,
  NoteRounded,
  ParkRounded,
  SchoolRounded,
  SecurityRounded,
  TheatersRounded,
  AirplaneTicket,
  ElectricBolt as ElectricBoltIcon,
  ElectricMeter as ElectricMeterIcon,
  CardMembership,
  WalletOutlined,
  Person,
  VerifiedUser,
  Person2,
  Message,
  BarChartRounded,
  ConfirmationNumber as ConfirmationNumberIcon,
  SignalCellularAlt2Bar as SignalCellularAlt2BarIcon,
  WifiTethering as WifiTetheringIcon,
  ReceiptLong as ReceiptLongIcon,
  FileCopy as FileCopyIcon,
  StackedBarChartRounded,
  Refresh,
  Info,
  AccessTime as AccessTimeIcon,
  NotificationsRounded,
  SettingsRounded,
  ShieldOutlined,
} from '@mui/icons-material';

/**
 * Navigation configuration for the sidebar.
 * Each item can be:
 * - `type: 'link'` → single link
 * - `type: 'collapse'` → collapsible section with children
 */
export const SIDEBAR_ITEMS = [
  {
    type: 'link',
    id: 'dashboard',
    title: 'Dashboard',
    path: '/',
    icon: DashboardRounded,
    permission: null, // accessible by all authenticated users
  },
  {
    type: 'collapse',
    id: 'vouchers',
    title: 'Vouchers & Tickets',
    icon: AirplaneTicket,
    permission: 'Vouchers & Tickets',
    children: [
      {
        type: 'link',
        id: 'generate-pins',
        title: 'Pins & Serials Generator',
        path: 'evoucher/generate',
        icon: KeySharp,
        permission: 'Generate Pins & Serials',
      },
      {
        type: 'link',
        id: 'waec-checkers',
        title: 'WAEC Checker',
        path: 'evoucher/waec',
        icon: NoteRounded,
        permission: 'WAEC Checkers',
      },
      {
        type: 'link',
        id: 'university-forms',
        title: 'University Forms',
        path: 'evoucher/university',
        icon: SchoolRounded,
        permission: 'University & Polytechnic Forms',
      },
      {
        type: 'link',
        id: 'security-forms',
        title: 'Security Service',
        path: 'evoucher/security',
        icon: SecurityRounded,
        permission: 'Security Service Forms',
      },
      {
        type: 'link',
        id: 'cinema-tickets',
        title: 'Cinema & Event Tickets',
        path: 'evoucher/cinema',
        icon: TheatersRounded,
        permission: 'Cinema Tickets',
      },
      {
        type: 'link',
        id: 'stadium-tickets',
        title: 'Stadium Tickets',
        path: 'evoucher/stadium',
        icon: ParkRounded,
        permission: 'Stadium Tickets',
      },
      {
        type: 'link',
        id: 'bus-tickets',
        title: 'Bus Tickets',
        path: 'evoucher/bus',
        icon: CarRentalRounded,
        permission: 'Bus Tickets',
      },
    ],
  },
  {
    type: 'collapse',
    id: 'prepaid',
    title: 'Prepaid Units',
    icon: ElectricBoltIcon,
    permission: 'Prepaid Units',
    children: [
      {
        type: 'link',
        id: 'meters',
        title: 'Meters',
        path: 'electricity/meters',
        icon: ElectricMeterIcon,
        permission: 'View Meters',
      },
      {
        type: 'link',
        id: 'prepaid-transactions',
        title: 'Transactions',
        path: 'electricity/transactions',
        icon: CardMembership,
        permission: 'View Prepaid Transaction',
      },
    ],
  },
  {
    type: 'collapse',
    id: 'airtime',
    title: 'Airtime',
    icon: WalletOutlined,
    permission: 'Airtime',
    children: [
      {
        type: 'link',
        id: 'bulk-sales',
        title: 'Bulk Sales',
        path: 'airtime/transactions',
        icon: CardMembership,
        permission: 'View Bulk Airtime Transaction',
      },
      {
        type: 'link',
        id: 'agents',
        title: 'Agent Distributors',
        path: 'airtime/agent',
        icon: Person,
        permission: 'Agents',
      },
    ],
  },
  {
    type: 'link',
    id: 'roles',
    title: 'Roles & Permissions',
    path: 'roles',
    icon: ShieldOutlined,
    permission: 'Employees', // only visible to users with Employees permission
  },
  {
    type: 'link',
    id: 'employees',
    title: 'Employees',
    path: 'employees',
    icon: VerifiedUser,
    permission: 'Employees',
  },
  {
    type: 'link',
    id: 'users',
    title: 'Users',
    path: 'users',
    icon: Person2,
    permission: 'Users',
  },
  {
    type: 'collapse',
    id: 'wallets',
    title: 'Wallets Details',
    icon: WalletOutlined,
    permission: ['User Wallets', 'Agent Wallets'], // show if any of these permissions
    children: [
      {
        type: 'link',
        id: 'user-wallets',
        title: 'Users',
        path: 'wallets',
        icon: CardMembership,
        permission: 'User Wallets',
      },
      {
        type: 'link',
        id: 'agent-wallets',
        title: 'Agent',
        path: 'wallets/agent',
        icon: Person,
        permission: 'Agent Wallets',
      },
    ],
  },
  {
    type: 'link',
    id: 'messages',
    title: 'Messages',
    path: 'messages',
    icon: Message,
    permission: 'Messages',
  },
  {
    type: 'collapse',
    id: 'summary',
    title: 'Summary & Reports',
    icon: BarChartRounded,
    permission: 'Summary',
    children: [
      {
        type: 'link',
        id: 'voucher-summary',
        title: 'Vouchers & Tickets',
        path: 'summary/vouchers-tickets',
        icon: ConfirmationNumberIcon,
        permission: 'View All Tickets & Voucher Transactions',
      },
      {
        type: 'link',
        id: 'prepaid-summary',
        title: 'Prepaid Units',
        path: 'summary/prepaid-units',
        icon: ElectricBoltIcon,
        permission: 'View All Prepaid Units Transactions',
      },
      {
        type: 'link',
        id: 'airtime-summary',
        title: 'Airtime Transfers',
        path: 'summary/airtime',
        icon: WifiTetheringIcon,
        permission: 'View All Airtime Transactions',
      },
      {
        type: 'link',
        id: 'bundle-summary',
        title: 'Data Bundle',
        path: 'summary/data-bundle',
        icon: SignalCellularAlt2BarIcon,
        permission: 'View All Data Bundle Transactions',
      },
      {
        type: 'link',
        id: 'agent-transactions',
        title: 'Agent Transactions',
        path: 'summary/agent-transactions',
        icon: StackedBarChartRounded,
        permission: null, // visible to all with Summary permission
      },
      {
        type: 'link',
        id: 'all-transactions',
        title: 'All Transactions',
        path: 'summary/transactions',
        icon: ReceiptLongIcon,
        permission: 'View All Transactions',
      },
      {
        type: 'link',
        id: 'reports',
        title: 'Reports',
        path: 'summary/report',
        icon: FileCopyIcon,
        permission: 'View All Transactions Report',
      },
    ],
  },
  {
    type: 'collapse',
    id: 'refund',
    title: 'Refund Transactions',
    icon: Refresh,
    permission: null, // only visible if user.isAdmin (handled in render)
    isAdminOnly: true,
    children: [
      {
        type: 'link',
        id: 'all-refunds',
        title: 'All Refunds',
        path: 'refund',
        icon: FileCopyIcon,
        permission: null,
      },
      {
        type: 'link',
        id: 'refund-money',
        title: 'Refund Money',
        path: 'refund/money',
        icon: FileCopyIcon,
        permission: null,
      },
    ],
  },
  {
    type: 'link',
    id: 'help-support',
    title: 'Help & Support',
    path: 'help-and-support',
    icon: Info,
    permission: null,
  },
  {
    type: 'link',
    id: 'activity-logs',
    title: 'Activity Logs',
    path: 'logs',
    icon: AccessTimeIcon,
    permission: null,
  },
];

// Additional items that appear at the bottom (profile, notifications, settings, logout)
export const BOTTOM_ITEMS = [
  {
    type: 'link',
    id: 'profile',
    title: 'Profile',
    path: 'profile',
    icon: Person,
    permission: null,
  },
  {
    type: 'link',
    id: 'notifications',
    title: 'Notifications',
    path: 'notifications',
    icon: NotificationsRounded,
    permission: null,
    badge: true, // indicates a badge should be shown
  },
  {
    type: 'link',
    id: 'settings',
    title: 'Settings',
    path: 'settings',
    icon: SettingsRounded,
    permission: 'Settings',
  },
];